-- MySQL Script generated by MySQL Workbench
-- Fri Oct 20 09:17:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema GB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GB` DEFAULT CHARACTER SET utf8 ;
USE `GB` ;

-- -----------------------------------------------------
-- Table `GB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GB`.`users` (
  `id` INT NULL AUTO_INCREMENT,
  `userName` VARCHAR(150) NOT NULL,
  `pass` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GB`.`produsts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GB`.`produsts` (
  `id` INT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `desc` TEXT NOT NULL,
  `img` VARCHAR(150) NOT NULL,
  `available` TINYINT NULL,
  `user_id` INT NOT NULL,
  `price` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `userData_idx` (`user_id` ASC) ,
  CONSTRAINT `userData`
    FOREIGN KEY (`user_id`)
    REFERENCES `GB`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GB`.`Message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `GB`.`Message` (
  `id` INT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
